### ISSUE TITLE
"docker-compose up" failures associated with girder "2.x-maintenance" branch

### ISSUE THREAD

**Issue by jcfr** [girder/slicer_package_manager#73]
The following error is reported:
```
$ git clone --branch 2.x-maintenance https://github.com/girder/girder.git girder-2x
$ cd girder-2x
$ docker-compose up
[...]
ERROR: Could not find a version that satisfies the requirement hachoir-metadata (from girder==2.5.0) (from versions: none)
ERROR: No matching distribution found for hachoir-metadata (from girder==2.5.0)
```

**Comment by jcfr** [comment]
After addressing the previous error, the following error is reported:

```
Running "webpack:plugin_vega" (webpack) task
Version: webpack 2.7.0
         Asset       Size  Chunks                    Chunk Names
 plugin.min.js     778 kB       0  [emitted]  [big]  plugins/vega/plugin
plugin.min.css  119 bytes       0  [emitted]         plugins/vega/plugin

WARNING in ./~/vega-statistics/src/quantiles.js
11:20-34 "export 'quantileSorted' was not found in 'd3-array'
  at HarmonyImportSpecifierDependency._getErrors (/girder/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:61:15)
  at HarmonyImportSpecifierDependency.getWarnings (/girder/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:35:15)
  at Compilation.reportDependencyErrorsAndWarnings (/girder/node_modules/webpack/lib/Compilation.js:672:24)
  at Compilation.finish (/girder/node_modules/webpack/lib/Compilation.js:535:9)
  at /girder/node_modules/webpack/lib/Compiler.js:491:16
  at /girder/node_modules/tapable/lib/Tapable.js:289:11
  at _addModuleChain (/girder/node_modules/webpack/lib/Compilation.js:481:11)
  at processModuleDependencies.err (/girder/node_modules/webpack/lib/Compilation.js:452:13)
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by jcfr** [comment]
Closing. Following the integration of #78 , this issue will be irrelevant.
